### ISSUE TITLE
Afficher 21 catégories NACE dans la colonne des entreprises

### ISSUE THREAD

**Issue by marcu** [brunomoyse/ecolens#7]
pour les 21 catégories voir site BCE

**Comment by brunomoyse** [comment]
SELECT code, description
FROM kbo.code
WHERE  code ~ '^[A-Za-z]+$' 
AND category = 'Nace2008' 
AND language = 'FR';

**Comment by brunomoyse** [comment]
Je ne vois que des codes NACE numéraires liés aux entreprises je ne vois pas la liaison avec les codes en lettres

Les 21 catégories sont classés avec une lettre allant de A à U

**Comment by brunomoyse** [comment]
https://www.nbb.be/doc/dq/e_method/m_necd10.pdf

![image](https://github.com/brunomoyse/ecolens/assets/61888532/50f8b6f0-268b-45ed-a9b4-104099361583)

**Comment by brunomoyse** [comment]
https://www.infobelpro.com/fr/blog/codes-nace

Voici le mapping pour le réaliser nous même:


Section | Title | Divisions
-- | -- | --
A | Agriculture, sylviculture et pêche | 01 – 03
B | Industries extractives | 05 – 09
C | Industrie manufacturière | 10 – 33
D | Production et distribution d’électricité, de gaz, de vapeur et d’air conditionné | 35
E | Production et distribution d’eau; assainissement, gestion des déchets et dépollution | 36 – 39
F | Construction | 41 – 43
G | Commerce; réparation d’automobiles et de motocycles | 45 – 47
H | Transports et entreposage | 49 – 53
I | Hébergement et restauration | 55 – 56
J | Information et communication | 58 – 63
K | Activités financières et d’assurance | 64 – 66
L | Activités immobilières | 68
M | Activités spécialisées, scientifiques et techniques | 69 – 75
N | Activités de services administratifs et de soutien | 77 – 82
O | Administration publique | 84
P | Enseignement | 85
Q | Santé humaine et action sociale | 86 – 88
R | Arts, spectacles et activités récréatives | 90 – 93
S | Autres activités de services | 94 – 96
T | Activités des ménages en tant qu’employeurs; activités indifférenciées des ménages en tant que producteurs de biens et services pour usage propre | 97 – 98
U | Activités extra territoriales | 99
